{% set version = "1.11.25" %}

package:
  name: aws-sdk-cpp
  version: {{ version }}

source:
  url: https://github.com/aws/aws-sdk-cpp/archive/{{ version }}.tar.gz
  sha256: 1103cf18516ca70d76c062af5a2b5c2418c5162235895baf3550a9f356d69f10

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-sdk-cpp", max_pin="x.x.x") }}

requirements:
  build:
    - cmake >=3.2
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - make  # [unix]
  host:
    - aws-c-common
    - aws-c-event-stream
    - aws-crt-cpp
    - libcurl
    - openssl
    - zlib

test:
  files:
    - test.cpp
    - CMakeLists.txt
  requires:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - make  # [unix]
  commands:

about:
  home: https://github.com/aws/aws-sdk-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C++ library that makes it easy to integrate C++ applications with AWS services
  description: |
    The AWS SDK for C++ provides a modern C++ (version C++ 11 or later) interface for Amazon Web Services (AWS).
    It is meant to be performant and fully functioning with low- and high-level SDKs,
    while minimizing dependencies and providing platform portability (Windows, OSX, Linux, and mobile).
  doc_url: https://aws.amazon.com/documentation/sdk-for-cpp/
  dev_url: https://github.com/aws/aws-sdk-cpp

extra:
  recipe-maintainers:
    - h-vetinari
    - pitrou
    - ihnorton
    - xhochy
