bot:
  abi_migration_branches:
  - v1.10.x
  automerge: true
  version_updates:
    # due to high volume of abi-relevant version upgrades, only
    # update for about 1 in 10 new versions, at random (see #662)
    random_fraction_to_keep: 0.1
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test_on_native_only: true
